apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp-ns
  labels:
    app: employees
    tier: frontend
spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: webapp
        image: 334566130486.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysql-ns.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "password123"
        - name: DBPORT
          value: "3306"
        - name: DATABASE
          value: "employees"
