apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
  namespace: webapp-ns
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
        tier: frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: webapp
        image: 334566130486.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysql-ns.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "password123"
        - name: DBPORT
          value: "3306"
        - name: DATABASE        # Added just in case!
          value: "employees"